### ISSUE TITLE
EXPlist configuration

### ISSUE THREAD

**Issue by blackboar** [JevLOMCN/JevsUpdatedCrystalDatabase#1]
Hello Jev, can you share your EXPlist configuration, because it is very important to the game, but it is not in the list

**Comment by JevLOMCN** [comment]
This Repo is not a full release of Supercode's Crystal Mir 2. It is an updated database which requires the Envir folder to work.
If you're looking for an EXP table, It's not here. It's located within Supercode's Github under Mir 2 -> Server -> Configs -> ExpList
